name: run-tests

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/run-tests.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 8.4, 8.3 ]
        laravel: [ 12.*, 11.*, 10.* ]
        stability: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: 12.*
            testbench: 10.*
            pest_version: 3
          - laravel: 11.*
            testbench: 9.*
            pest_version: 3
          - laravel: 10.*
            testbench: 8.*
            pest_version: 2
            exclude:
              # PHP 8.4 with Laravel 10 and prefer-lowest can be problematic
              - php: 8.4
                laravel: 10.*
                stability: prefer-lowest
              # PHP 8.3 with Laravel 10 and prefer-lowest can be problematic
              - php: 8.3
                laravel: 10.*
                stability: prefer-lowest
              - php: 8.4
                laravel: 10.*
                stability: prefer-lowest
              # PHP 8.3 with Laravel 10 and prefer-lowest can be problematic
              - php: 8.3
                laravel: 10.*
                stability: prefer-lowest
              - php: 8.4
                laravel: 10.*
                stability: prefer-lowest


    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        env:
          CI: "true"
        run: |
          # First require the specific Laravel version
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          # Then require the specific testbench version
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          # Then require the specific Pest version
          composer require "pestphp/pest:^${{ matrix.pest_version }}.0" "pestphp/pest-plugin-laravel:^${{ matrix.pest_version }}.0" "pestphp/pest-plugin-arch:^${{ matrix.pest_version }}.0" --dev --no-interaction --no-update
          # Update dependencies
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
          # Remove problematic packages after install if they got pulled in
          composer remove orchestra/canvas --dev --no-interaction || true

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        env:
          CI: "true"
        run: |
          # Try to run tests directly without relying on package:discover
          vendor/bin/pest --ci || php -d memory_limit=-1 vendor/bin/pest --ci
